services:
  - type: web
    name: crud-django-nani
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn crudproj.wsgi:application"
    plan: free
    branch: master
    region: oregon
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
