services:
  - type: web
    name: crud-django-nani
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: "gunicorn crudproj.wsgi:application"
    plan: free
    branch: master
    region: oregon
