# Generated by Django 5.1.5 on 2025-04-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rollno', models.IntegerField(primary_key=True, serialize=False)),
                ('Sub1', models.IntegerField()),
                ('Sub2', models.IntegerField()),
            ],
        ),
    ]
